<?php

namespace RLI\StockBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function findParDesEtPu($des, $pu) {
        $qb = $this->createQueryBuilder('p');

  $qb->where('p.prodDes LIKE :des')
       ->setParameter('des', '%'.$des.'%')
       ->andWhere('p.prodPu < :pu')
       ->setParameter('pu', $pu)
       ->orderBy('p.prodPu', 'DESC');
       return $qb ->getQuery()->getResult() ;
}

}
